services:
  db:
    image: postgres:alpine3.16
    container_name: 'ex11-db'
    expose: 
      - "5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  python:
    image: ex11/python:1.0
    build: ./python
    container_name: 'ex11-python'
    working_dir: '/tmp/work'
    volumes:
      - ./python/src:/tmp/work
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: /bin/bash
